export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const SET_NEWSLETTERS = "SET_NEWSLETTERS";
export const FETCH_NEWSLETTER_ID = "FETCH_NEWSLETTER_ID";
export const FETCH_REQUEST_TITLE = "FETCH_REQUEST_TITLE";